<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.javid</groupId>
    <artifactId>schedulean</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Schedulean</name>
    <description>Job Job runner and runtime scheduler</description>

    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer>
            <name>Javid Rafiei</name>
            <email>javid.rafiee@google.com</email>
        </developer>
    </developers>

    <modules>
        <!-- The <module> tag refers to the directory name -->
        <!-- The artifactId inside the child pom.xml will have the schedulean- prefix -->
        <module>domain</module>
        <module>application-api</module>
        <module>application-core</module>

        <!-- Inbound Adapters -->
        <!--
        <module>adapter-in-rest</module>
        <module>adapter-in-grpc</module>
        <module>adapter-in-nats</module>
        -->

        <!-- Outbound Adapters -->
        <!--
        <module>adapter-out-oracle</module>
        <module>adapter-out-postgres</module>
        <module>adapter-out-mongodb</module>
        <module>adapter-out-nats</module>
        <module>adapter-out-shedlock</module>
        -->

        <!-- Bootstrap -->
        <!--
        <module>bootstrap</module>
        -->
    </modules>

    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>

    <properties>
        <java.version>25</java.version>
        <spring.boot.version>4.1.0</spring.boot.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <dependencyManagement>
        <dependencies>
            <!-- Internal Modules -->
            <dependency>
                <groupId>org.javid</groupId>
                <artifactId>schedulean-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.javid</groupId>
                <artifactId>schedulean-application-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.javid</groupId>
                <artifactId>schedulean-application-core</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot.version}</version>
            </plugin>
        </plugins>
    </build>

</project>
